- pipeline: production-build
  name: Production Build
  refs:
  - refs/heads/main
  fail_on_prepare_env_warning: true
  events:
  - type: WEBHOOK
  actions:
  - action: Build Docker image
    type: DOCKERFILE
    dockerfile_path: ""
    do_not_prune_images: true
